language: ruby
cache: bundler

rvm:
  - 2.4
  - 2.5
  - &latest_ruby 2.6
  - 2.7
  - ruby-head

matrix:
  include:
    - rvm: *latest_ruby
      script: bundle exec rake memory_profile:run
      name: Profiling Memory Usage
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.7

branches:
  only:
    - master
    - gh-pages
    - /.*-stable/

notifications:
  disable: true
