language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-head
#  - rbx-2

sudo: false

matrix:
  allow_failures:
    - rvm: jruby-head

script: "bundle exec rake"

notifications:
  disable: true
